version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/output
    environment:
      FL_OUTPUT_DIR: $CIRCLE_WORKING_DIRECTORY
      FASTLANE_LANE: adhoc
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run: |
          brew install x11vnc

          x11vnc -geometry 1280x1024
          export DISPLAY=:1.0
