version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/output
    environment:
      FL_OUTPUT_DIR: $CIRCLE_WORKING_DIRECTORY
      FASTLANE_LANE: adhoc
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run: |
          brew update && sudo brew install firefox-esr
          sudo brew install vnc4server metacity

          vnc4server -geometry 1280x1024 -depth 24
          export DISPLAY=:1.0
          metacity &

          # if Firefox isn't installed:
          # sudo apt-get update && sudo apt-get install firefox-esr
          firefox &
